"use client";
import {useEffect,useState} from 'react';
import {challengeTimestamp} from '@/lib/challengeTime';
const n=(v:any)=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:4});
function Revenue({v}:{v:any}) {return <><strong>${n(v?.total)}</strong><p className="text-xs text-gray-400">(${n(v?.confirmed)} confirmed + ${n(v?.estimated)} estimated)</p>{v?.pending>0&&<p className="text-xs text-amber-400">{v.pending} commissions pending</p>}</>;}
export default function CommercialOverview({challengeId,timezone}:{challengeId:string;timezone:string}) {
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[modal,setModal]=useState<'volumeUSD'|'total'|null>(null),[queued,setQueued]=useState(false);
 useEffect(()=>{let active=true;const load=()=>fetch(`/api/management/challenge/${challengeId}/commercial`,{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('Report unavailable');return r.json();}).then(d=>{if(active){setData(d);setError('');setQueued(false);}}).catch(e=>{if(active)setError(e.message);});load();const timer=setInterval(load,30000);return()=>{active=false;clearInterval(timer);};},[challengeId]);
 if(data?.enabled===false)return null;
 const refresh=async()=>{setQueued(true);try{const r=await fetch(`/api/management/challenge/${challengeId}/commercial-refresh`,{method:'POST'});if(!r.ok)throw Error('Could not queue refresh');}catch(e:any){setError(e.message);setQueued(false);}};
 const rows=[...(data?.rows||[])].sort((a,b)=>Number(b.challenge[modal||'total'])-Number(a.challenge[modal||'total'])||a.registrationId-b.registrationId);
 return <section className="space-y-3 min-w-0">
 <div className="flex flex-wrap justify-between gap-2 text-xs text-gray-400"><span>Real-account commercial analytics {data?.updatedAt&&`· ${challengeTimestamp(data.updatedAt,timezone,true)}`}</span><button onClick={refresh} disabled={queued||data?.refreshing} className="text-blue-400 disabled:opacity-50">{queued||data?.refreshing?'Refreshing…':'Refresh commercial data'}</button></div>
 {(error||data?.error)&&<p className="text-amber-400 text-xs">{error||data.error}. Last successful report is retained.</p>}
 {!data?.hasData?<p className="text-sm text-gray-400">Commercial data {data?.refreshing||queued?'is loading…':'has not been loaded yet.'}</p>:<>
 <div className="grid sm:grid-cols-2 gap-4">
 <button onClick={()=>setModal('volumeUSD')} className="text-left p-5 rounded-2xl border border-white/10 bg-white/5 min-w-0 break-words"><h3 className="text-xs text-gray-400 mb-2">CHALLENGE VOLUME</h3><p className="text-2xl font-bold text-blue-400">${n(data.challenge.volumeUSD)}</p><p>{n(data.challenge.lots)} lots</p><p className="text-xs text-gray-400 mt-2">All participant MT5 accounts: ${n(data.all.volumeUSD)} · {n(data.all.lots)} lots</p>{data.all.volumePending>0&&<p className="text-xs text-amber-400">USD volume pending for {data.all.volumePending} trades</p>}</button>
 <button onClick={()=>setModal('total')} className="text-left p-5 rounded-2xl border border-white/10 bg-white/5 min-w-0 break-words"><h3 className="text-xs text-gray-400 mb-2">CHALLENGE REVENUE</h3><div className="text-2xl text-emerald-400"><Revenue v={data.challenge}/></div><p className="text-xs text-gray-400 mt-3">All participant MT5 accounts</p><Revenue v={data.all}/></button>
 </div>{data.warnings?.map((w:string)=><p key={w} className="text-amber-400 text-xs">{w}</p>)}<p className="text-xs text-gray-500">All-account totals include challenge accounts. Refreshes hourly. Estimates are replaced when confirmed by Exness.</p></>}
 {modal&&<div className="fixed inset-0 z-[100] bg-black/80 flex items-center justify-center p-3" onClick={()=>setModal(null)}><section role="dialog" aria-modal="true" aria-label="Commercial analytics" className="bg-[#111827] border border-white/10 rounded-2xl w-full max-w-6xl max-h-[90vh] overflow-auto p-5" onClick={e=>e.stopPropagation()}>
 <div className="flex justify-between gap-3 mb-3"><h2 className="font-bold">Participants by challenge {modal==='volumeUSD'?'USD volume':'revenue'}</h2><button aria-label="Close" onClick={()=>setModal(null)}>✕</button></div><p className="text-xs text-gray-400 mb-4">{data.notice}</p>
 <div className="overflow-auto"><table className="w-full text-xs text-left"><thead><tr className="text-gray-400">{['Participant / rank','Challenge account','All MT5 accounts','Coverage'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map((r:any)=><tr key={r.registrationId} className="border-t border-white/10 align-top"><td className="p-3 min-w-[160px]"><strong>{r.nickname}</strong><p>{r.account}</p><p className="text-gray-400">Rank {r.rank?`#${r.rank}`:'—'} · {r.status}</p></td>{['challenge','all'].map(scope=><td key={scope} className="p-3 min-w-[210px]"><p>${n(r[scope].volumeUSD)} volume · {n(r[scope].lots)} lots</p><Revenue v={r[scope]}/><p className="text-gray-400">Top instrument: {r[scope].topInstrument||'—'}</p>{r[scope].volumePending>0&&<p className="text-amber-400">{r[scope].volumePending} USD volumes pending</p>}</td>)}<td className="p-3 min-w-[180px]"><p>{r.coverageSource}</p><p>{r.cutoff?challengeTimestamp(r.cutoff,timezone,true):'No verified coverage'}</p><p>{r.linkedAccounts} linked MT5 accounts</p>{r.issues.map((i:string)=><p key={i} className="text-amber-400">{i}</p>)}</td></tr>)}</tbody></table></div></section></div>}
 </section>;
}
