const {test}=require('node:test');const assert=require('node:assert/strict');require('ts-node/register/transpile-only');
let challenge,regs,ledger,count,now,deliver,results,calls,sends,afterVerify;
const realNow=Date.now;Date.now=()=>now;
function mock(p,exports){const id=require.resolve(p);require.cache[id]={id,filename:id,loaded:true,exports};}
const key=(id,slot)=>`${id}/${slot}`;
const db={transaction:async fn=>fn(),getClient:async()=>({query:async()=>({rows:[{locked:true}]}),release(){}}),query:async(sql,args=[])=>{
 if(sql.startsWith('SELECT * FROM trading_challenges'))return {rows:[{...challenge}]};
 if(sql.startsWith('SELECT COUNT'))return {rows:[{cnt:count}]};
 if(sql.startsWith('UPDATE trading_challenges SET pre_start_lead_hours')){challenge.pre_start_lead_hours??=args[1];return {rows:[]};}
 if(sql.startsWith('INSERT INTO prestart_balance_checks')){for(const r of regs){const k=key(r.id,args[1]);if(!ledger.has(k))ledger.set(k,{registration_id:r.id,slot:args[1]});}return {rows:[]};}
 if(sql.startsWith('SELECT r.id'))return {rows:regs.filter(r=>{const b=ledger.get(key(r.id,args[1]));return b&&(!b.checked_at||(b.problem&&!b.notified_at))&&(!b.attempted_at||now-+b.attempted_at>=300000);})};
 if(sql.startsWith('SELECT * FROM prestart_balance_checks'))return {rows:[{...ledger.get(key(...args))}]};
 if(sql.startsWith('UPDATE prestart_balance_checks SET checked_at=NULL')){for(const b of ledger.values())if(b.slot===args[1])Object.assign(b,{checked_at:null,attempted_at:null,error:null});return {rows:[]};}
 if(sql.startsWith('UPDATE prestart_balance_checks')){const b=ledger.get(key(args[0],args[1]));if(sql.includes('attempted_at=NOW()'))b.attempted_at=new Date(now);else if(sql.includes('checked_at=COALESCE'))Object.assign(b,{checked_at:new Date(now),balance:args[2],problem:args[3],error:null});else if(sql.includes('notified_at=NOW()'))Object.assign(b,{notified_at:new Date(now),error:null});else if(sql.includes('SET error='))b.error=args[2];return {rows:[]};}
 if(sql.startsWith('UPDATE trading_registrations SET last_known_balance')){const r=regs.find(r=>r.id===args[0]);r.last_known_balance=args[1];r.balance_warning=args[2];return {rows:[]};}
 if(sql.startsWith('INSERT INTO wp_pull_batches'))return {rows:[]};
 throw Error(sql);
}};
mock('../src/database/db',{db});mock('../src/services/wpEvaluationEngine',{evaluationEngine:{rulesForAccount:async()=>({})}});
mock('../src/services/vpsService',{vpsService:{verifyConnection:async(account)=>{calls++;if(afterVerify)afterVerify();return results[account]||{success:true,status:'connected',balance:100};}}});
mock('../src/services/emailService',{emailService:{sendGeneric:async(...args)=>{sends.push(args);return deliver;}}});
const {runBalanceWarningCheck:run,balanceNotice}=require('../src/services/prestartBalanceChecks');
function reset(n=2){now=+new Date('2099-10-01T07:00:00Z');count=n;challenge={id:1,host_id:2,status:'registration_open',start_date:'2099-10-01T12:00:00Z',timezone:'UTC',title:'Test <unsafe>',type:'demo',starting_balance:100,target_balance:200,deposit_mode:'fixed',starting_balance_policy:'decimal'};regs=[1,2].map(id=>({id,account_number:String(id),account_type:'demo',is_cent:false,source:'winnerpip',email:`${id}@example.invalid`}));ledger=new Map();results={'1':{success:true,status:'connected',balance:120}};deliver=true;calls=0;sends=[];afterVerify=null;}
test('T-5 checks all accounts and emails only mismatches, once across repeated ticks',async()=>{reset();await run(1,null);assert.equal(calls,2);assert.equal(sends.length,1);assert.equal(regs[0].balance_warning,true);assert.equal(regs[1].balance_warning,false);assert.equal(challenge.pre_start_lead_hours,2);assert.match(sends[0][2],/10:00/);assert.match(sends[0][2],/Reset your demo/);assert.match(sends[0][2],/Test &lt;unsafe&gt;/);now+=600000;await run(1,null);assert.equal(calls,2);assert.equal(sends.length,1);});
test('T-6 for large challenges; threshold crossing does not shorten correction window',async()=>{reset(501);now-=3600000;await run(1,null);assert.equal(challenge.pre_start_lead_hours,3);assert.match(sends[0][2],/09:00/);reset();await run(1,null);count=501;now+=600000;await run(1,null);assert.equal(challenge.pre_start_lead_hours,2);assert.equal(sends.length,1);});
test('failed email retries after five minutes and successful deliveries are not repeated',async()=>{reset();deliver=false;await run(1,null);assert.equal([...ledger.values()].filter(b=>b.notified_at).length,0);now+=60000;await run(1,null);assert.equal(sends.length,1);now+=300000;deliver=true;await run(1,null);assert.equal(sends.length,2);assert.equal(sends[0][3],sends[1][3]);});
test('VPS timeout stays retryable and never sets password_changed or disqualifies',async()=>{reset();results['1']={success:false,status:'timeout'};await run(1,null);assert.equal(sends.length,0);assert.equal(regs[0].pull_status,undefined);assert.equal(regs[0].disqualified,undefined);now+=300001;results['1']={success:true,status:'connected',balance:100};await run(1,null);assert.equal(regs[0].balance_warning,false);});
test('manual recheck clears a corrected balance; pending email does not use stale balance',async()=>{reset();deliver=false;await run(1,null);results['1']={success:true,status:'connected',balance:100};now+=300001;await run(1,null);assert.equal(regs[0].balance_warning,false);assert.equal(sends.length,1);results['1']={success:true,status:'connected',balance:120};await run(1,null,true);assert.equal(regs[0].balance_warning,true);});
test('schedule moved during VPS call cannot apply a stale warning',async()=>{reset();afterVerify=()=>{challenge.start_date='2099-10-02T12:00:00Z';};await run(1,null);assert.equal(sends.length,0);assert.equal(regs[0].balance_warning,undefined);});
test('before warning window or after final verification no new checks are run',async()=>{reset();now-=3600000;await run(1,null);assert.equal(calls,0);reset();now+=3*3600000;await run(1,null);assert.equal(calls,0);reset();challenge.pre_start_check_started_at=new Date();await run(1,null);assert.equal(calls,0);});
test('admin participants receive Telegram, hosted participants email',async()=>{reset();delete challenge.host_id;for(const r of regs){r.source='telegram';r.user_id=r.id;}const messages=[];await run(1,{sendMessage:async(...args)=>messages.push(args)});assert.equal(messages.length,1);assert.equal(sends.length,0);});
test('hybrid real and demo checks use independent limits and modes',async()=>{reset();challenge.type='hybrid';challenge.split_category_settings=true;Object.assign(challenge,{demo_starting_balance:100,demo_target_balance:200,demo_deposit_mode:'fixed',demo_target_enabled:true,demo_allow_below_start:false,real_starting_balance:200,real_target_balance:400,real_deposit_mode:'min_limit',real_target_enabled:true,real_allow_below_start:false});regs[1].account_type='real';results['2']={success:true,status:'connected',balance:199.99};await run(1,null);assert.equal(sends.length,2);assert.match(sends[1][2]+sends[0][2],/at least USD 200.00/);});
