const assert=require('node:assert/strict');
const url=process.env.TEST_DATABASE_URL;
if(!url || !['127.0.0.1','localhost'].includes(new URL(url).hostname))throw Error('Local synthetic database required');
process.env.TZ='UTC';process.env.PGOPTIONS='-c timezone=UTC';process.env.DATABASE_URL=url;process.env.NODE_ENV='test';require('ts-node/register/transpile-only');
const {db}=require('../../src/database/db');
const {vpsService}=require('../../src/services/vpsService');
const {emailService}=require('../../src/services/emailService');
let deliveries=0,failEmail=true,calls=0;
vpsService.verifyConnection=async(account)=>{calls++;return {success:true,status:'connected',balance:account==='991001'?120:100.25,currency:'USD',trade_mode:0};};
emailService.sendGeneric=async()=>{deliveries++;return !failEmail;};
const {runBalanceWarningCheck}=require('../../src/services/prestartBalanceChecks');
const {TradingScheduler}=require('../../src/scheduler/tradingScheduler');
(async()=>{
 await require('../../src/database/hardeningMigration').migrateHardening();
 const rules={stop_loss_required:false,weekend_trading:true,only_cent_account:false,allow_professional:false,rules_enabled:Object.fromEntries(['max_lot_size','max_open_trades','pair_limit','stop_loss_required','daily_loss_cap','max_hold_hours','min_trade_duration','weekend_trading','min_active_days','min_total_trades'].map(k=>[k,false]))};
 const start=new Date(Date.now()+4*3600000).toISOString();
 const {challenge}=await require('../../src/services/challengeGatekeeper').executeCreate({title:'SYNTHETIC balance '+Date.now(),type:'demo',start_date:start,end_date:new Date(Date.now()+86400000).toISOString(),starting_balance:100,target_balance:0,target_enabled:false,rules});
 const id=challenge.id;await require('../../src/services/challengeState').transitionChallenge(id,'registration_open');
 for(const [i,acct] of ['991001','991002','991003'].entries())await db.query(`INSERT INTO trading_registrations(challenge_id,user_id,email,nickname,account_number,account_type,connection_verified,investor_password,source) VALUES($1,$2,$3,$4,$5,'demo',true,'SYNTHETIC','winnerpip')`,[id,-900-i,`${acct}@example.invalid`,acct,acct]);
 await runBalanceWarningCheck(id,null);assert.equal(calls,3);assert.equal(deliveries,1);
 let rows=(await db.query('SELECT * FROM prestart_balance_checks WHERE challenge_id=$1 ORDER BY registration_id',[id])).rows;
 assert.equal(rows[0].notified_at,null);assert.equal(rows[0].problem,'high');assert.equal(rows[1].problem,null);
 await db.query("UPDATE prestart_balance_rounds SET finished_at=NOW()-INTERVAL '6 minutes' WHERE challenge_id=$1",[id]);failEmail=false;
 await runBalanceWarningCheck(id,null);assert.equal(deliveries,2);assert.equal(calls,4);
 await runBalanceWarningCheck(id,null);assert.equal(deliveries,2);assert.equal(calls,4);
 // Correct the warned account, leave the previously valid one one whole unit too high.
 vpsService.verifyConnection=async(account)=>({success:true,status:'connected',balance:account==='991001'?100.1:account==='991003'?95:101,currency:'USD',trade_mode:0});
 await db.query("UPDATE trading_challenges SET start_date=NOW()+INTERVAL '90 minutes' WHERE id=$1",[id]);
 const fresh=(await db.query('SELECT * FROM trading_challenges WHERE id=$1',[id])).rows[0];
 const scheduler=new TradingScheduler({bot:{telegram:{sendMessage:async()=>{throw Error('Unexpected live notification');}}}});
 await scheduler.checkPreStartSnapshot(fresh);
 const accounts=(await db.query('SELECT account_number,disqualified,actual_starting_balance FROM trading_registrations WHERE challenge_id=$1 ORDER BY account_number',[id])).rows;
 assert.equal(accounts[0].disqualified,false);assert.equal(Number(accounts[0].actual_starting_balance),100.1);assert.equal(accounts[1].disqualified,true);assert.equal(accounts[2].disqualified,false);assert.equal(Number(accounts[2].actual_starting_balance),95);
 await assert.rejects(()=>require('../../src/services/challengeSettings').updateChallengeSettings(id,{end_date:new Date(Date.now()+172800000).toISOString()}),/pre-start check/);
 // Real SQL: reconcile gain after final snapshot, exclude pre-start entry, catch later deposit.
 const reg=(await db.query("SELECT * FROM trading_registrations WHERE challenge_id=$1 AND account_number='991001'",[id])).rows[0];
 const entry=new Date(+new Date(fresh.start_date)-60000).toISOString();
 const cutoff=new Date(+new Date(fresh.start_date)+60000).toISOString();
 await db.query("UPDATE trading_registrations SET history_sync_state='verified',history_verified_through=$2,history_verified_balance=150.1 WHERE id=$1",[reg.id,cutoff]);
 await db.query("INSERT INTO wp_deals(challenge_id,registration_id,account_number,ticket,deal_type,profit,time) VALUES($1,$2,'991001',9910011,'0',50,$3)",[id,reg.id,entry]);
 await db.query("INSERT INTO wp_trades(challenge_id,registration_id,account_number,ticket,symbol,trade_type,volume,profit,open_time,close_time) VALUES($1,$2,'991001',9910011,'TEST','buy',1,50,$3,$3)",[id,reg.id,entry]);
 const {evaluationEngine}=require('../../src/services/wpEvaluationEngine');evaluationEngine.notifyDqByEmail=async()=>{};
 await evaluationEngine.evaluateSingleAccount(id,reg.id);
 let state=(await db.query('SELECT disqualified,actual_starting_balance FROM trading_registrations WHERE id=$1',[reg.id])).rows[0];
 assert.equal(state.disqualified,false);assert.equal(Number(state.actual_starting_balance),100.1);
 const score=(await db.query('SELECT total_trades,gross_profit FROM wp_leaderboard_staging WHERE registration_id=$1',[reg.id])).rows[0];
 assert.equal(Number(score.total_trades),0);assert.equal(Number(score.gross_profit),0);
 assert.equal((await db.query('SELECT is_qualified FROM wp_trades WHERE registration_id=$1',[reg.id])).rows[0].is_qualified,false);
 await db.query('UPDATE trading_registrations SET history_verified_balance=170.1 WHERE id=$1',[reg.id]);
 await assert.rejects(()=>evaluationEngine.evaluateSingleAccount(id,reg.id),/unexplained/);
 assert.equal((await db.query('SELECT disqualified FROM trading_registrations WHERE id=$1',[reg.id])).rows[0].disqualified,false);
 await db.query("INSERT INTO wp_deals(challenge_id,registration_id,account_number,ticket,deal_type,profit,time) VALUES($1,$2,'991001',9910012,'2',20,$3)",[id,reg.id,entry]);
 await evaluationEngine.evaluateSingleAccount(id,reg.id);
 assert.equal((await db.query('SELECT disqualified FROM trading_registrations WHERE id=$1',[reg.id])).rows[0].disqualified,true);
 console.log('PASS: real SQL warning ledger, retry, duplicate protection, decimal final check and schedule lock; no external requests.');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>db.close());
